[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TRY A-TURo"
authors = [{name = "TOMMMMMMMM", email = "fdfddfdfdfdfdfdf@lumache"}]
dynamic = ["version", "description"]
